export const cities = {
  select_city: [],
  BagerHat: [
    "kochuwa",
    "chitolmari",
    "Fakirhat",
    "Bagerhat sadar",
    "mongla",
    "Morelganj",
    "Mollahat",
    "Rampal",
    "Shoron Khola",
  ],
  BandarBan: [
    "Ali Kadam",
    "Kalaghat",
    "Lama",
    "Naikong",
    "Rowangchhari",
    "Ruma",
    "Thanchi",
  ],
  Barguna: [
    "Amtali",
    "Bamna",
    "Betage",
    "Barguna Sadar",
    "Patharghata",
    "Taltoly",
  ],
  Barisal: [
    "Agailjhara",
    "Babuganj",
    "Bakerganj",
    "Banaripara",
    "Barishal Bandor Thana",
    "Barishal Sadar",
    "Gauronadi",
    "Hijla",
    "Kotowali",
    "Mahendiganj",
    "Muladi",
    "Wazirpur powrosohba",
  ],
  Bhola: [
    "Bhola Sadar",
    "Burhanuddin",
    "Char fashion",
    "Dokkhin aicha",
    "Doulatkhan",
    "Tazumuddin",
    "Lalmohon",
  ],
  Bogura: [
    "Adamdigi",
    "Bogura Gabtoli",
    "Bogura Sadar",
    "Dhunat",
    "Dhupchachiya",
    "Kahalu",
    "Nandigram",
    "Sariakandi",
    "Sahajanpur",
    "Shantahar",
    "Sherpur",
    "Shibganj",
    "Shonatola",
  ],

  Chittagong: [
    "Agrabad",
    "Akbarsah",
    "Andarkilla",
    "Anowara",
    "Bakoliya Thana",
    "Bashkhali",
    "Bayezid",
    "Bowalkhali",
    "Bondor",
    "Chandanaish",
    "Chawkbazar",
    "Chittagang Sadar ghat",
    "Double Mooring",
    "East Jora",
    "EPZ",
    "Enayetpur",
    "Fatichari",
    "Hathazari",
    "Halisahar",
    "Karnophuli",
    "Keranihat",
    "Khulsi",
    "Kotowali",
    "Lohagara",
    "Mirsarai",
    "Nasirabad",
    "Nazirhat",
    "New Market CTG",
    "Pahartali",
    "Panchlaish",
    "Patiya",
    "Ranguniya",
    "Rawzan",
    "Shandip",
    "Satkaniya",
    "Sitakundo",
    "Zorarganj",
  ],
  Chuwadanga: [
    "AlomDanga",
    "ChuwaDanga Sadar",
    "Damurhuda",
    "Darshana",
    "Doulatganj",
    "Jiban nagar",
  ],
  Coxs_Bazar: [
    "Chakoria",
    "Coxs Bazar Sadar",
    "Eidgaon",
    "Kutubdia",
    "Moheshkhali",
    "Pekua",
    "Ramu (Coxs Bazar)",
    "Teknaf",
    "Ukhia (Coxs Bazar)",
  ],
  Dhaka: [
    "Turag",
    "Tejkunipara",
    "Tejgaon",
    "Dhamrai",
    "Dhanmondi",
    "Doha",
    "Daraz office",
    "Dayaganj",
    "New Market",
    "Narinda",
    "New Eschaton",
    "Nikunj",
    "Niketan",
    "Polashi",
    "Pallavi",
    "Nilkhet",
    "Old Paltan",
    "preemption",
    "Farmgate",
    "Postgola",
    "Bakshibazar",
    "Banashree",
    "Banani",
    "Banani DOHS",
    "Ancestry",
    "Buet Campass",
    "Mothijheel",
    "Magbazar",
    "Mohakhali DHOS",
    "Mohakhali",
    "Malibag",
    "Maniknagar",
    "Mirpur",
    "Mirpur DOHS",
    "Mirpur-1",
    "Mirpur-10",
    "Mirpur-11",
    "Mirpur-12",
    "Mirpur-2",
    "mugda",
    "Mohammadpur",
    "Jatrabari",
    "Ramana",
    "Rampura",
    "Rayerbagh",
    "Rupnag",
    "Lakshi Bazar",
    "Lalbagh",
    "blushing",
    "Rayerbazar",
    "Shanirakhra",
    "Shantinagar",
    "Shahjadpur",
    "Rajarbagh",
    "Shahjanpur",
    "Shahbagh",
    "Shimrail",
    "Sukrabad",
    "Rajabazar",
    "Shere Bangla Nagar",
    "Shyampur",
    "Sadarghat",
    "Islampur",
    "eschaton",
    "Uora- Sector 17",
    "Uora- Sector 18",
    "Eat the answer",
    "answer",
    "Uttara - Ranabola",
    "Uttara-Abdullah",
    "Uttara-Kaola",
    "Uttara-Kamarpara",
    "Uttara-Diabari",
    "Uttara-Baunia",
    "Elephant Road",
    "Wari",
    "KadamTala",
    "Kamalapur",
    "Art garden",
    "Kalyanpur",
    "Kaowranbazar",
    "cockerel",
    "Kazipara",
    "Kathalbagan",
    "Kafrul",
    "Kamrangirchar",
    "Kuril World Road",
    "Keraniganj",
    "Cantonment",
    "Khilkhet",
    "Khilkhet-Dumni",
    "Khilkhet-Namapara",
    "Khilkhet-patira",
    "Khilkhet-Pingcity",
    "Khilkhet-Barua",
    "Khilgaon",
    "Khilgaon - Gogan",
    "Khilgaon - Trimohani",
    "Khilgaon - Dakshingaon",
    "Khilgaon - Nandipara",
    "Khilgaon - Nasirabad",
    "Khilgaon - Begunbari",
    "Khilgaon - Meradia",
    "Khilgaon - Sheikh",
    "Gabbatli",
    "Gulshan-1",
    "Gulshan-2",
    "shooting range",
    "Gendaria",
    "Green Road",
    "Chowkazar",
    "Jigatala",
    "Jurain",
    "Tikatuli",
    "DU Campus",
    "Demra",
    "Demra - Amulya",
    "Demra - Kayetpara",
    "Demra - Bhavani",
    "Demra market",
    "Hathirpul",
    "Hazaribagh",
  ],
  Jamalpur: [
    "Bakshiganj",
    "Dewangonj",
    "Islampur",
    "Jamalpur Sadar",
    "Madarganj",
    "Melandaha",
    "Sarishabari",
  ],
  Khagrachari: [
    "Dighinala",
    "Khagrachari Sadar",
    "Laksmichari",
    "Manikchari",
    "Matiranga",
    "Mohalchari",
    "Panchari",
    "Ramgor",
  ],
  Khulna: [
    "Batiaghata",
    "Boyra",
    "Chandkhali",
    "Dacope",
    "Daulatpur",
    "Digholia",
    "Dumuria",
    "Fultola",
    "Khalishpur",
    "Khulna Sadar",
    "Kopilmuni",
    "Koyra",
    "Paikgachha Upozila",
    "Rupsha",
    "Sonadanga",
    "Tala Upozilla",
    "Terokhada",
  ],

  Kurigram: [
    "Char Rajibpur",
    "Chilmari",
    "Kurigram Sadar",
    "Nagesshari",
    "Phulbari",
    "Rajarhat",
    "Rawmari",
    "Ulipur",
  ],
  Kushtiya: [
    "Daulatpur",
    "Islamic University",
    "Khoksha",
    "Kumarkhali",
    "Kushtia Sadar",
    "Kushtia-Mirpur",
  ],
  LalMonirhat: [
    "Aditmari",
    "Hatibandha (Lalmonirhat)",
    "Kaliganj(Lalmonirhat)",
    "Lalmonirhat Sadar",
    "Patgram",
  ],
  Madaripur: [
    "Dasar Thana",
    "Kalkini Thana",
    "Madaripur Sadar",
    "Rajoir Thana",
    "Shibchar",
  ],
  Manikganj: [
    "Daulatpur(Manikganj)",
    "Ghior",
    "Harirampur (Manikganj)",
    "Manikganj Sadar",
    "Saturia",
    "Shibalaya",
    "Singair",
  ],
  Moulavibazar: [
    "Baralekha",
    "Juri",
    "Kamalganj",
    "Kulaura",
    "Moulvibazar Sadar",
    "Rajnagar",
    "Sreemangal",
  ],

  Mymensingh: [
    "Bhaluka",
    "Dhobaura",
    "Fulbaria",
    "Gafargaon",
    "Gauripur",
    "Haluaghat",
    "Ishwarganj",
    "Muktagachha",
    "Mymensingh Sadar",
    "Nandail",
    "Phulpur",
    "Trishal",
  ],
  Naongan: [
    "Atrai",
    "Bodolgachi",
    "Dhamairhat",
    "Manda",
    "Mohadebpur",
    "Naogaon Sadar",
    "Niyamatpur",
    "Porsha",
    "Potnitola",
    "Raninagaor",
    "Sapahar",
  ],

  Netrokona: [
    "Atpara",
    "Barhatta",
    "Kalmakanda",
    "Kendua",
    "Khaliajuri",
    "Madan",
    "Mohanganj",
    "Netrokona Sadar",
    "Purbadhala",
    "Susang Durgapur",
  ],

  Noakhali: [
    "Begumganj",
    "Chatkhil",
    "Companiganj (Noakhali)",
    "Hatiya (Noakhali)",
    "Kabir Hat (Noakhali)",
    "Maijdee (Noakhali)",
    "Nijumdip (Hatiya)",
    "Senbag",
    "Sonaimuri",
    "Subarnachar (Noakhali)",
  ],

  Rajsahi: [
    "Bagha",
    "Bagmara",
    "Banseshwar",
    "Charghat",
    "Durgapur",
    "Godagari",
    "Katakhali",
    "Mohonpur",
    "Paba",
    "Puthia",
    "Rajpara",
    "Rajshahi Sadar (Boalia)",
    "Shah Mokdum",
    "Sharda",
    "Taherpur",
  ],
  Rangamati: [
    "Baghaichari",
    "Barkal",
    "Belaichari",
    "Jurachari",
    "Kaptai",
    "Kaptai Kaptai Project",
    "Kaptai Nuton Bazar",
    "Kaptai Sadar",
    "Kawkhali (Rangamati)",
    "Langadu",
    "Naniarchar",
    "Rajasthali",
    "Rangamati Sadar",
  ],

  Sylhet: [
    "Balaganj",
    "Beanibazar",
    "Bishwanath",
    "Companyganj",
    "Dakshin Surma",
    "Fenchuganj",
    "Golapganj",
    "Gowainghat",
    "Jaintapur",
    "Kanaighat",
    "Osmani Nagar",
    "Sylhet Sadar",
    "Zakiganj",
  ],
};
